version: "3.9-slim"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/flask
    environment:
      - FLASK_ENV=development
